openapi: 3.0.3
info:
  title: GoHome
  description: This is API for Group Project
  version: "1.0.0"
  contact:
    email: grfhnry@gmail.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ALFIANADSAPUTRA_1/AirBnB/1.0.0
  # Main URL
  - description: Main URL
    url: URL will be update soon
tags:
  - name: Auth
  - name: User
  - name: Homestay
  - name: Reservation
  - name: Feedback

# AUTH
paths:
  /login:
    post:
      tags:
        - "Auth"
      description: "Features login for users"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
            example:
              email: "grf@example.com"
              password: "grf123"
      responses:
        200:
          description: "login"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseObject"
              example:
                data:
                  id: 1
                  name: "griffin"
                  email: "grf@example.com"
                  phone: "0812345"
                  address: "makassar"
                message: "login success"
                token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VySUQiOjR9.QTZxERh4CwC_UnL_eJvTi_A_qdLeBZ-IjR4nqoxjodk"
        400:
          $ref: "#/components/responses/400"
        404:
          $ref: "#/components/responses/404"
        500:
          $ref: "#/components/responses/500"

components:
    securitySchemes:
        JWTAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
            description: "user token"
    schemas:
        responseObject:
            type: object
            properties:
                data:
                    type: object
                message:
                    type: string
        errorResponse:
            type: object
            properties:
                message:
                    type: string
    examples:
        formatUploadError:
            value:
                message: bad request because of format not pdf, png, jpg, or jpeg
        validationError:
            value:
                message: field_name value must be the_condition
        failedUploadError:
            value:
                message: failed to upload image because internal server error
        credentialError:
            value:
                message: access is denied due to invalid credential
        internalServerError:
            value:
                message: internal server error
        pathNotFound:
            description: url path not found
            value:
                message: Not Found

            # responseObjectArr:
            # type: object
            # properties:
            #     data:
            #         type: array
            #         items:
            #             type: object
            #     message:
            #         type: string
    responses:
        400:
            description: "error from user"
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            message:
                                type: string
                    example:
                        message: "bad request"
        401:
            description: "unauthorized"
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            message:
                                type: string
                    example:
                        message: access is denied due to invalid credential
        404:
            description: "url path not found"
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/errorResponse"
                    example:
                        message: not found
        500:
            description: "error from server"
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            message:
                                type: string
                    example:
                        message: "internal server error"